# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'

end
